//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/InputSystem_Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputSystem_Actions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @InputControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystem_Actions"",
    ""maps"": [
        {
            ""name"": ""BattleAction"",
            ""id"": ""67587e3e-a508-47ce-9bbc-324c982a84b9"",
            ""actions"": [
                {
                    ""name"": ""DisCard"",
                    ""type"": ""Button"",
                    ""id"": ""8136db95-1189-4c16-87d0-db9afcf2067e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CardSelectOne"",
                    ""type"": ""Button"",
                    ""id"": ""7d94e3bc-90a7-42a4-b713-defba64a48d1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CardSelectTwo"",
                    ""type"": ""Button"",
                    ""id"": ""622fa351-90b2-4d17-a82d-e584f72a86dc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CardSelectTree"",
                    ""type"": ""Button"",
                    ""id"": ""ce52ad26-6f8f-4f94-bf2f-7e6a9cf95cf1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7293fc9d-9fe7-4df3-b294-8fc428e75072"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""DisCard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e74ef7b7-ad9e-4571-93ef-5919f75b781a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""CardSelectOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f73c2eef-cda9-4858-a377-ff26561e53d7"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""CardSelectTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f460a72a-8bb5-4858-a538-4270555d6c6a"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""CardSelectTree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""TutorialAction"",
            ""id"": ""a073e853-2b82-49f6-ba0b-021a1c6758e2"",
            ""actions"": [
                {
                    ""name"": ""Proceed"",
                    ""type"": ""Button"",
                    ""id"": ""d311ac5e-fc53-4702-a6bd-d912be81e0a4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b32c2265-88df-4357-bed3-3e167db00e67"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Proceed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // BattleAction
        m_BattleAction = asset.FindActionMap("BattleAction", throwIfNotFound: true);
        m_BattleAction_DisCard = m_BattleAction.FindAction("DisCard", throwIfNotFound: true);
        m_BattleAction_CardSelectOne = m_BattleAction.FindAction("CardSelectOne", throwIfNotFound: true);
        m_BattleAction_CardSelectTwo = m_BattleAction.FindAction("CardSelectTwo", throwIfNotFound: true);
        m_BattleAction_CardSelectTree = m_BattleAction.FindAction("CardSelectTree", throwIfNotFound: true);
        // TutorialAction
        m_TutorialAction = asset.FindActionMap("TutorialAction", throwIfNotFound: true);
        m_TutorialAction_Proceed = m_TutorialAction.FindAction("Proceed", throwIfNotFound: true);
    }

    ~@InputControls()
    {
        UnityEngine.Debug.Assert(!m_BattleAction.enabled, "This will cause a leak and performance issues, InputControls.BattleAction.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_TutorialAction.enabled, "This will cause a leak and performance issues, InputControls.TutorialAction.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BattleAction
    private readonly InputActionMap m_BattleAction;
    private List<IBattleActionActions> m_BattleActionActionsCallbackInterfaces = new List<IBattleActionActions>();
    private readonly InputAction m_BattleAction_DisCard;
    private readonly InputAction m_BattleAction_CardSelectOne;
    private readonly InputAction m_BattleAction_CardSelectTwo;
    private readonly InputAction m_BattleAction_CardSelectTree;
    /// <summary>
    /// Provides access to input actions defined in input action map "BattleAction".
    /// </summary>
    public struct BattleActionActions
    {
        private @InputControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public BattleActionActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "BattleAction/DisCard".
        /// </summary>
        public InputAction @DisCard => m_Wrapper.m_BattleAction_DisCard;
        /// <summary>
        /// Provides access to the underlying input action "BattleAction/CardSelectOne".
        /// </summary>
        public InputAction @CardSelectOne => m_Wrapper.m_BattleAction_CardSelectOne;
        /// <summary>
        /// Provides access to the underlying input action "BattleAction/CardSelectTwo".
        /// </summary>
        public InputAction @CardSelectTwo => m_Wrapper.m_BattleAction_CardSelectTwo;
        /// <summary>
        /// Provides access to the underlying input action "BattleAction/CardSelectTree".
        /// </summary>
        public InputAction @CardSelectTree => m_Wrapper.m_BattleAction_CardSelectTree;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_BattleAction; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="BattleActionActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(BattleActionActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="BattleActionActions" />
        public void AddCallbacks(IBattleActionActions instance)
        {
            if (instance == null || m_Wrapper.m_BattleActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BattleActionActionsCallbackInterfaces.Add(instance);
            @DisCard.started += instance.OnDisCard;
            @DisCard.performed += instance.OnDisCard;
            @DisCard.canceled += instance.OnDisCard;
            @CardSelectOne.started += instance.OnCardSelectOne;
            @CardSelectOne.performed += instance.OnCardSelectOne;
            @CardSelectOne.canceled += instance.OnCardSelectOne;
            @CardSelectTwo.started += instance.OnCardSelectTwo;
            @CardSelectTwo.performed += instance.OnCardSelectTwo;
            @CardSelectTwo.canceled += instance.OnCardSelectTwo;
            @CardSelectTree.started += instance.OnCardSelectTree;
            @CardSelectTree.performed += instance.OnCardSelectTree;
            @CardSelectTree.canceled += instance.OnCardSelectTree;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="BattleActionActions" />
        private void UnregisterCallbacks(IBattleActionActions instance)
        {
            @DisCard.started -= instance.OnDisCard;
            @DisCard.performed -= instance.OnDisCard;
            @DisCard.canceled -= instance.OnDisCard;
            @CardSelectOne.started -= instance.OnCardSelectOne;
            @CardSelectOne.performed -= instance.OnCardSelectOne;
            @CardSelectOne.canceled -= instance.OnCardSelectOne;
            @CardSelectTwo.started -= instance.OnCardSelectTwo;
            @CardSelectTwo.performed -= instance.OnCardSelectTwo;
            @CardSelectTwo.canceled -= instance.OnCardSelectTwo;
            @CardSelectTree.started -= instance.OnCardSelectTree;
            @CardSelectTree.performed -= instance.OnCardSelectTree;
            @CardSelectTree.canceled -= instance.OnCardSelectTree;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="BattleActionActions.UnregisterCallbacks(IBattleActionActions)" />.
        /// </summary>
        /// <seealso cref="BattleActionActions.UnregisterCallbacks(IBattleActionActions)" />
        public void RemoveCallbacks(IBattleActionActions instance)
        {
            if (m_Wrapper.m_BattleActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="BattleActionActions.AddCallbacks(IBattleActionActions)" />
        /// <seealso cref="BattleActionActions.RemoveCallbacks(IBattleActionActions)" />
        /// <seealso cref="BattleActionActions.UnregisterCallbacks(IBattleActionActions)" />
        public void SetCallbacks(IBattleActionActions instance)
        {
            foreach (var item in m_Wrapper.m_BattleActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BattleActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="BattleActionActions" /> instance referencing this action map.
    /// </summary>
    public BattleActionActions @BattleAction => new BattleActionActions(this);

    // TutorialAction
    private readonly InputActionMap m_TutorialAction;
    private List<ITutorialActionActions> m_TutorialActionActionsCallbackInterfaces = new List<ITutorialActionActions>();
    private readonly InputAction m_TutorialAction_Proceed;
    /// <summary>
    /// Provides access to input actions defined in input action map "TutorialAction".
    /// </summary>
    public struct TutorialActionActions
    {
        private @InputControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public TutorialActionActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "TutorialAction/Proceed".
        /// </summary>
        public InputAction @Proceed => m_Wrapper.m_TutorialAction_Proceed;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_TutorialAction; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="TutorialActionActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(TutorialActionActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="TutorialActionActions" />
        public void AddCallbacks(ITutorialActionActions instance)
        {
            if (instance == null || m_Wrapper.m_TutorialActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TutorialActionActionsCallbackInterfaces.Add(instance);
            @Proceed.started += instance.OnProceed;
            @Proceed.performed += instance.OnProceed;
            @Proceed.canceled += instance.OnProceed;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="TutorialActionActions" />
        private void UnregisterCallbacks(ITutorialActionActions instance)
        {
            @Proceed.started -= instance.OnProceed;
            @Proceed.performed -= instance.OnProceed;
            @Proceed.canceled -= instance.OnProceed;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="TutorialActionActions.UnregisterCallbacks(ITutorialActionActions)" />.
        /// </summary>
        /// <seealso cref="TutorialActionActions.UnregisterCallbacks(ITutorialActionActions)" />
        public void RemoveCallbacks(ITutorialActionActions instance)
        {
            if (m_Wrapper.m_TutorialActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="TutorialActionActions.AddCallbacks(ITutorialActionActions)" />
        /// <seealso cref="TutorialActionActions.RemoveCallbacks(ITutorialActionActions)" />
        /// <seealso cref="TutorialActionActions.UnregisterCallbacks(ITutorialActionActions)" />
        public void SetCallbacks(ITutorialActionActions instance)
        {
            foreach (var item in m_Wrapper.m_TutorialActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TutorialActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="TutorialActionActions" /> instance referencing this action map.
    /// </summary>
    public TutorialActionActions @TutorialAction => new TutorialActionActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "BattleAction" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="BattleActionActions.AddCallbacks(IBattleActionActions)" />
    /// <seealso cref="BattleActionActions.RemoveCallbacks(IBattleActionActions)" />
    public interface IBattleActionActions
    {
        /// <summary>
        /// Method invoked when associated input action "DisCard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDisCard(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CardSelectOne" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCardSelectOne(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CardSelectTwo" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCardSelectTwo(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CardSelectTree" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCardSelectTree(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "TutorialAction" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="TutorialActionActions.AddCallbacks(ITutorialActionActions)" />
    /// <seealso cref="TutorialActionActions.RemoveCallbacks(ITutorialActionActions)" />
    public interface ITutorialActionActions
    {
        /// <summary>
        /// Method invoked when associated input action "Proceed" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnProceed(InputAction.CallbackContext context);
    }
}
